HOST: 0.0.0.0
PORT: 8080
LOG_DIR: logs

# Use mongodb to store, queue and analysis
MONGODB:

# remember user device for 400 days
WEBAPP_DEVICE_COOKIE_EXPIRES_IN_MILLISECONDS: 34560000000
WEBAPP_DEVICE_COOKIE_KEY: device
WEBAPP_DEVICE_COOKIE_SECRET: 1234567890abcdefgh
WEBAPP_DEVICE_COOKIE_SECURED: false

# logout after 30 minutes
WEBAPP_SESSION_EXPIRES_IN_MILLISECONDS: 1800000

# delete the session when browser closed
WEBAPP_SESSION_COOKIE_EXPIRES_IN_MILLISECONDS: 0
WEBAPP_SESSION_COOKIE_KEY: session
WEBAPP_SESSION_COOKIE_SECRET: 1234567890abcdefgh
WEBAPP_SESSION_COOKIE_SECURED: false

# validate and re-issue auth token every 5 minutes
WEBAPP_TOKEN_EXPIRES_IN_MILLISECONDS: 300000

# Authentication
WEBAPP_LOGIN_URL: /login
WEBAPP_LOGIN_SUCCESS_URL: /
WEBAPP_LOGIN_FAILED_URL: /login
